/* The HVX instruction census: the op table and the corpus file format.
 *
 * GENERATED by tools/htp-lab/isa/gen_census.py. Do not edit. Change the generator and run it again.
 *
 * The census runs each HVX instruction that touches floating point (sf, hf, qf32, qf16, bf, f8),
 * each conversion between integer and float, and the integer instructions with rounding or
 * saturation, on a fixed input corpus. compare.py compares each output with the CPU oracle (strict
 * IEEE, round to nearest even at each step) and with the outputs of the other Hexagon versions (or
 * of a real chip). isa_bench gives the cost of each op.
 *
 * isa_kernels.c has no dependency other than the Hexagon SDK headers. The kernel lab includes it
 * (lab/target_isa.c), and a DSP library can compile it without change.
 *
 * Use:
 *   1. Load the corpus streams (the files corpus_<stream>.bin, format below).
 *   2. For each op k: isa_run(k, stream[in_stream[0]], stream[in_stream[1]], stream[in_stream[2]],
 *      out, isa_ops[k].n_vectors). An iteration reads in_bytes[j] bytes from input j and writes
 *      out_bytes bytes. All pointers must have an alignment of 128 bytes. The caller must hold an
 *      HVX context in the 128-byte mode.
 *   3. Write the output as out_<name>.bin (format below), or compare isa_hash() of the output.
 */
#ifndef ISA_KERNELS_H
#define ISA_KERNELS_H

#include <stddef.h>
#include <stdint.h>

#define ISA_VEC_BYTES      128
#define ISA_STREAM_VECTORS 4096 /* vectors in each corpus stream */
#define ISA_STREAM_BYTES   (ISA_STREAM_VECTORS * ISA_VEC_BYTES)
#define ISA_N_OPS          383

/* The corpus streams. target_isa.c makes them with integer code only, thus each version gets the
 * same bytes. Refer to target_isa.c for the contents of each stream. */
enum isa_stream {
    ISA_S_NONE = 0,
    ISA_S_SF_A = 1,
    ISA_S_SF_B = 2,
    ISA_S_SF_C = 3,
    ISA_S_HF_A = 4,
    ISA_S_HF_B = 5,
    ISA_S_HF_C = 6,
    ISA_S_QF32_A = 7,
    ISA_S_QF32_B = 8,
    ISA_S_QF32_C = 9,
    ISA_S_QF16_A = 10,
    ISA_S_QF16_B = 11,
    ISA_S_QF16_C = 12,
    ISA_S_BF_A = 13,
    ISA_S_BF_B = 14,
    ISA_S_BF_C = 15,
    ISA_S_F8_A = 16,
    ISA_S_F8_B = 17,
    ISA_S_F8_C = 18,
    ISA_S_INT_A = 19,
    ISA_S_INT_B = 20,
    ISA_S_INT_C = 21,
    ISA_S_SEQ16 = 22,
    ISA_S_WCONV = 23,
    ISA_S_COUNT
};

/* The element types of the operands and of the result */
enum isa_type {
    ISA_T_NONE = 0,
    ISA_T_SF = 1,
    ISA_T_HF = 2,
    ISA_T_QF32 = 3,
    ISA_T_QF16 = 4,
    ISA_T_BF = 5,
    ISA_T_F8 = 6,
    ISA_T_X = 7,
    ISA_T_B = 8,
    ISA_T_UB = 9,
    ISA_T_H = 10,
    ISA_T_UH = 11,
    ISA_T_W = 12,
    ISA_T_UW = 13,
    ISA_T_PRED = 14,
    ISA_T_COUNT
};

/* The kinds of op */
enum isa_kind {
    ISA_KIND_INSN = 0, /* the intrinsic, which compiles to one instruction on each version */
    ISA_KIND_IEEE = 1, /* the IEEE-form instruction as inline asm (target attribute hvx-ieee-fp) */
    ISA_KIND_CC   = 2, /* the intrinsic of an IEEE-form instruction: what the compiler emits */
    ISA_KIND_SEQ  = 3  /* a sequence of instructions (a helper of the llama.cpp kernels) */
};

typedef struct isa_op_desc {
    const char * name;       /* the op name and the output file stem */
    const char * source;     /* the intrinsic or the helper */
    const char * asm_syntax; /* the assembly syntax from the SDK header, "" for a sequence */
    const char * op_class;   /* the census class */
    uint8_t      kind;       /* enum isa_kind */
    uint8_t      min_arch;   /* the minimum __HVX_ARCH__ of the SDK header */
    uint8_t      out_type;   /* enum isa_type */
    uint8_t      in_type[3];
    uint8_t      in_stream[3]; /* enum isa_stream, ISA_S_NONE for an input that the op does not use */
    uint16_t     in_bytes[3];  /* bytes per iteration from each input: 0, 128 or 256 */
    uint16_t     out_bytes;    /* bytes per iteration to the output: 128 or 256 */
    uint16_t     n_vectors;    /* the iterations of the census run */
} isa_op_desc;

extern const isa_op_desc  isa_ops[ISA_N_OPS];
extern const char * const isa_stream_names[ISA_S_COUNT];
extern const char * const isa_type_names[ISA_T_COUNT];

/* Runs op op_id for n_vectors iterations. Returns 0, or -1 if the op is not available at the
 * __HVX_ARCH__ of this build, or -2 if op_id is not valid. */
int isa_run(int op_id, const void * in0, const void * in1, const void * in2, void * out, int n_vectors);

/* The cost bench: runs an inlined copy of op op_id on ISA_BENCH_UNROLL independent iterations for
 * each of n_iter trips, thus on ISA_BENCH_UNROLL * n_iter iterations of the inputs. The same
 * return codes as isa_run. The caller reads the cycle counter around the call. */
#define ISA_BENCH_UNROLL 4
int isa_bench(int op_id, const void * in0, const void * in1, const void * in2, void * out, int n_iter);

/* Returns 1 if the op is available in this build, else 0 */
int isa_available(int op_id);

/* The file format of a corpus stream and of an op output: one header of 128 bytes, then the raw
 * vectors (n_vectors * bytes_per_vector bytes). All fields are little endian. */
#define ISA_FILE_MAGIC_CORPUS "HVXC"
#define ISA_FILE_MAGIC_OUTPUT "HVXO"
#define ISA_FILE_VERSION      1

typedef struct isa_file_header {
    char     magic[4];         /* "HVXC" for a corpus stream, "HVXO" for an op output */
    uint32_t version;          /* ISA_FILE_VERSION */
    uint32_t id;               /* the stream id or the op id */
    uint32_t n_vectors;        /* the number of vectors (corpus) or iterations (output) */
    uint32_t bytes_per_vector; /* 128, or 256 for an output of vector pairs */
    uint32_t arch;             /* __HVX_ARCH__ of the program that wrote the file */
    uint32_t hash;             /* isa_hash() of the data */
    uint32_t source;           /* 0: hexagon-sim, 1: a real chip */
    char     name[64];         /* the stream name or the op name, zero padded */
    uint8_t  reserved[32];
} isa_file_header;

/* The hash of the census outputs: FNV-1a over 32-bit words in 32 independent lanes (lane k takes
 * the words k, k + 32, k + 64, ...), then FNV-1a over the 32 lane hashes. n must be a multiple of
 * 128. O(n). compare.py has the same function. */
static inline uint32_t isa_hash(const void * data, size_t n) {
    uint32_t h[32];
    for (int k = 0; k < 32; k++) {
        h[k] = 2166136261u;
    }
    const uint32_t * w = (const uint32_t *) data;
    for (size_t i = 0; i + 32 <= n / 4; i += 32) {
        for (int k = 0; k < 32; k++) {
            h[k] = (h[k] ^ w[i + k]) * 16777619u;
        }
    }
    uint32_t r = 2166136261u;
    for (int k = 0; k < 32; k++) {
        r = (r ^ h[k]) * 16777619u;
    }
    return r;
}

#endif
